begin
  DBMS_FGA.ADD_POLICY(
    OBJECT_SCHEMA => 'PROYEK',
    OBJECT_NAME => 'CART',
    POLICY_NAME => 'FGA_CART_POLICY',
    AUDIT_CONDITION => 'USER=''PROYEK''',
    STATEMENT_TYPES => 'SELECT,INSERT,UPDATE,DELETE',
    AUDIT_COLUMN => NULL,
    ENABLE => TRUE
  );
end;
/

begin
  DBMS_FGA.ADD_POLICY(
    OBJECT_SCHEMA => 'PROYEK',
    OBJECT_NAME => 'DTRANS',
    POLICY_NAME => 'FGA_DTRANS_POLICY',
    AUDIT_CONDITION => 'USER=''PROYEK''',
    STATEMENT_TYPES => 'SELECT,INSERT,UPDATE,DELETE',
    AUDIT_COLUMN => NULL,
    ENABLE => TRUE
  );
end;
/

begin
  DBMS_FGA.ADD_POLICY(
    OBJECT_SCHEMA => 'PROYEK',
    OBJECT_NAME => 'HTRANS',
    POLICY_NAME => 'FGA_HTRANS_POLICY',
    AUDIT_CONDITION => 'USER=''PROYEK''',
    STATEMENT_TYPES => 'SELECT,INSERT,UPDATE,DELETE',
    AUDIT_COLUMN => NULL,
    ENABLE => TRUE
  );
end;
/

begin
  DBMS_FGA.ADD_POLICY(
    OBJECT_SCHEMA => 'PROYEK',
    OBJECT_NAME => 'PENGIRIMANS',
    POLICY_NAME => 'FGA_PENGIRIMANS_POLICY',
    AUDIT_CONDITION => 'USER=''PROYEK''',
    STATEMENT_TYPES => 'SELECT,INSERT,UPDATE,DELETE',
    AUDIT_COLUMN => NULL,
    ENABLE => TRUE
  );
end;
/

begin
  DBMS_FGA.ADD_POLICY(
    OBJECT_SCHEMA => 'PROYEK',
    OBJECT_NAME => 'PRODUCTS',
    POLICY_NAME => 'FGA_PRODUCTS_POLICY',
    AUDIT_CONDITION => 'USER=''PROYEK''',
    STATEMENT_TYPES => 'SELECT,INSERT,UPDATE,DELETE',
    AUDIT_COLUMN => NULL,
    ENABLE => TRUE
  );
end;
/

begin
  DBMS_FGA.ADD_POLICY(
    OBJECT_SCHEMA => 'PROYEK',
    OBJECT_NAME => 'USERS',
    POLICY_NAME => 'FGA_USERS_POLICY',
    AUDIT_CONDITION => 'USER=''PROYEK''',
    STATEMENT_TYPES => 'SELECT,INSERT,UPDATE,DELETE',
    AUDIT_COLUMN => NULL,
    ENABLE => TRUE
  );
end;
/

SELECT OBJECT_NAME, TIMESTAMP, SQL_TEXT, STATEMENT_TYPE FROM DBA_FGA_AUDIT_TRAIL WHERE OBJECT_NAME='HTRANS';
